name: compile
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, you are running on `uname --all`"

  thesis:
    needs: greeting
    runs-on: ubuntu-latest
    container: siewyanhoh/latex_ubuntu:texlivefull
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: clean up cache 
        run: |
          make clean

      - name: build english latex pdf with docker
        run: |
          make VER=english
	  make VER=bahasa

      - uses: actions/upload-artifact@v2
        with:
          name: thesis.pdf
          path: thesis.pdf

      - uses: actions/upload-artifact@v2
        with:
	  name: tesis.pdf
	  path: tesis.pdf
